#!/bin/bash

# Define the filename and code
filename="1-alphabet.c"
code="#include \"main.h\"

/**
 * print_alphabet - print all alphabet in lowercase
 */

void print_alphabet(void)
{
    char letter;

    for (letter = 'a'; letter <= 'z'; letter++)
        _putchar(letter);

    _putchar('\\n');
}
"

# Create the file with the specified code
echo "$code" > "$filename"

# Inform the user that the file has been created
echo "File '$filename' has been created with the provided code."

