#!/bin/bash

# Define the filename and code
filename="2-print_alphabet_x10.c"
code="#include \"main.h\"

/**
 * print_alphabet_x10 - prints 10 times the alphabet, in lowercase,
 * followed by a new line
 */
void print_alphabet_x10(void)
{
    char ch;
    int i;

    i = 0;

    while (i < 10)
    {
        ch = 'a';
        while (ch <= 'z')
        {
            _putchar(ch);
            ch++;
        }
        _putchar('\\n');
        i++;
    }
}
"

# Create the file with the specified code
echo "$code" > "$filename"

# Inform the user that the file has been created
echo "File '$filename' has been created with the provided code."

